#!/bin/sh
set -e

printf "Running autoconf...\n"
autoconf -Wall --force

printf "Generating kconfig component lists...\n"
./maintainer/gen-kconfig.sh

printf "Generating kconfig component versions...\n"
./maintainer/gen-versions.sh

printf "Done. You may now run:\n    ./configure\n"
