#!/bin/bash

set -e
cd
rm -rf work/bld-samples
mkdir -p work/bld-samples work/inst-xtools
cd work/bld-samples
export PATH=$HOME/work/inst-ctng/bin:$PATH
ct-ng build-all CT_PREFIX=$HOME/work/inst-xtools ${1+CT_SAMPLES="$*"}
