#!/bin/bash

usr=$1
uid=$2
grp=$3
gid=$4
shift 4

groupadd -g ${gid} ${grp}
useradd -d /home/${usr} -m -g ${gid} -u ${uid} ${usr}
rm -f /home/${usr}/src
ln -sf /src /home/${usr}/src
if [ -z "$*" ]; then
    exec su -l ${usr}
else
    exec su -l -c "/bin/bash -c '$*'" ${usr}
fi
